# Generated by Django 6.0.1 on 2026-02-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['order']},
        ),
    ]
